[package]
name = "day09-part1"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
either = "1.9.0"
eyre = "0.6.10"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
